# Generated by Django 4.1.3 on 2023-02-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewFlight',
            new_name='Flight2',
        ),
    ]
