# Generated by Django 4.1.3 on 2023-02-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flight',
        ),
    ]
