# Generated by Django 4.1.3 on 2023-02-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0002_remove_passenger_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.ManyToManyField(blank=True, related_name='Passenger', to='Flight.flight1'),
        ),
    ]
